### ISSUE TITLE
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'. Did you mean: 'SSLv23_METHOD'?

### ISSUE THREAD

**Issue by RiteshSec** [narkopolo/fb_friend_list_scraper#9] opened 2023-08-29 12:13 UTC
- Have Installed the tool Successfully using ```sudo python3 -m pip install fb-friend-list-scraper```
- But when trying to run ```fbfriendlistscraper  -h``` getting the following error <img width="898" alt="image" src="https://github.com/n0kovo/fb_friend_list_scraper/assets/110530131/5cc39c99-497b-4651-92e1-3646b00d4c97">

**Comment by n0kovo** [comment] 2023-08-30 04:49
Closing as duplicate of #6 and #8.

**Closed as not planned by n0kovo** 2023-08-30 04:49 UTC
Labels: duplicate

**Comment by n0kovo** [comment] 2023-08-30 04:50
Closed as duplicate of #6 and #8.
